### ISSUE TITLE
Provider crash on changing CIFS permission for volume

### ISSUE THREAD

**Issue by MindBreakerVictor** [NetApp/terraform-provider-netapp-cloudmanager#60]
Hello,

The provider is crashing when trying to change the permission on a CIFS volume.

Below is the panic snippet from TF TRACE log:

> panic: runtime error: index out of range [0] with length 0
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: goroutine 65 [running]:
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: github.com/netapp/terraform-provider-netapp-cloudmanager/cloudmanager.resourceCVOVolumeUpdate(0xc000463c20, 0x1c34ac0, 0xc00000a3c0, 0x24, 0x23bb460)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	github.com/netapp/terraform-provider-netapp-cloudmanager/cloudmanager/resource_netapp_cloudmanager_volume.go:583 +0xdac
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00031c580, 0xc000215e30, 0xc0002899a0, 0x1c34ac0, 0xc00000a3c0, 0x1, 0x0, 0x0)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	github.com/hashicorp/terraform@v0.13.4/helper/schema/resource.go:314 +0x2b3
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00031cf00, 0xc0001b3a28, 0xc000215e30, 0xc0002899a0, 0xc000286050, 0x1e12428, 0xc000286050)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	github.com/hashicorp/terraform@v0.13.4/helper/schema/provider.go:297 +0x99
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00030e068, 0x1e11660, 0xc00024fa10, 0xc000215c70, 0xc00030e068, 0xc00024fa10, 0xc0005c1ba0)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	github.com/hashicorp/terraform@v0.13.4/helper/plugin/grpc_provider.go:923 +0x8e5
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1bfc940, 0xc00030e068, 0x1e11660, 0xc00024fa10, 0xc00030baa0, 0x0, 0x1e11660, 0xc00024fa10, 0xc00027a800, 0x719)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	github.com/hashicorp/terraform@v0.13.4/internal/tfplugin5/tfplugin5.pb.go:3303 +0x214
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b6c40, 0x1e1a418, 0xc000001680, 0xc00021f100, 0xc000554a50, 0x237c660, 0x0, 0x0, 0x0)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	google.golang.org/grpc@v1.31.0/server.go:1180 +0x52b
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: google.golang.org/grpc.(*Server).handleStream(0xc0001b6c40, 0x1e1a418, 0xc000001680, 0xc00021f100, 0x0)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	google.golang.org/grpc@v1.31.0/server.go:1503 +0xd0c
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000aa460, 0xc0001b6c40, 0x1e1a418, 0xc000001680, 0xc00021f100)
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	google.golang.org/grpc@v1.31.0/server.go:843 +0xab
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-07-22T14:06:04.973+0300 [DEBUG] plugin.terraform-provider-netapp-cloudmanager_v21.6.0: 	google.golang.org/grpc@v1.31.0/server.go:841 +0x1fd
2021-07-22T14:06:04.978+0300 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/netapp/netapp-cloudmanager/21.6.0/darwin_amd64/terraform-provider-netapp-cloudmanager_v21.6.0 pid=13950 error="exit status 2"
2021-07-22T14:06:04.979+0300 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/07/22 14:06:04 [DEBUG] module.ntap_cvo_frankfurt.module.volume_app["dev"].netapp-cloudmanager_volume.volume: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Canceled desc = context canceled

Below is the plan output:
![image](https://user-images.githubusercontent.com/611511/126630664-4a7aa2ac-3ffa-41e8-b625-e00e37655ac3.png)

And here's the output for terraform version:
![image](https://user-images.githubusercontent.com/611511/126630771-c5e78c3f-8d52-4eb0-a8af-efda6ff514b2.png)

Problem seems to be that shareInfoUpdateRequest struct has a list of AC objects, unlike shareInfoRequest which has only the direct struct. The code than tries to update the AC object at line 583 in `cloudmanager/resource_netapp_cloudmanager_volume.go` is then trying to access the first element in the list, but the list is empty.

**Comment by wenjun666** [comment]
Close this issue as the fix was released in 21.8.0
